### PR TITLE
Allowed for HTML to be used in the JSON

### PR DESCRIPTION
**Pull request by nyalex**
Allowed for HTML to be used in the JSON

### CODE REVIEW

**Comment by sandeepshetty** [comment]
Didn't try running it but it looks like invalid PHP?!

**Comment by nyalex** [comment]
What part of it exactly looks invalid?

**Comment by sandeepshetty** [comment]
Does this actually run for you? [Line #43 - #44](https://github.com/nyalex/shopify_api/blob/029d5025b2d5acfa376d2160cbd9845189d9a06d/client.php#L43)

**Comment by nyalex** [comment]
Oh I see what you're saying! That is my mistake. I modified your file to my own so I had to put back some code and I think I forgot to put back everything before committing it. The call() function is correct though. Here is the actual code that I am using for it: https://gist.github.com/4015302  Nothing else is changed. Sorry for the confusion.

**Comment by sandeepshetty** [comment]
Thanks. I'm thinking about removing stripslashes completely and not keeping it as an option because it is valid JSON without the stripslashes.

**Comment by sandeepshetty** [comment]
This issue and more fixed in the [latest version](https://github.com/phpish/shopify)

**Pull request closed without merging**
