### PR TITLE
Issue Fixing

### PR DESCRIPTION
**Pull request by ghost**
This pull request includes a couple of fixes for the following:
- A error caused by a missing exception class
- The base url was not being correctly generated for private apps

### CODE REVIEW

**Comment by tomkerswill** [comment]
Thanks so much, James - I have been using the extension for about an hour and just hit both these two errors!

**Comment by JorgenSmith** [comment]
Thanks @james-phpgenie for your fixes; json encoding the error lets us correctly identify the root cause as returned by Shopify - e.g. 

```
array(1) {
  'errors' =>
  array(1) {
    'email' =>
    array(1) {
      [0] =>
      string(22) "has already been taken"
    }
  }
}
```

This is pretty critical information.

@sandeepshetty , would it be possible to merge this with master now? Would love to use the packagist version in a project simply pulling dev-master without workarounds to fetch the PR as part of the provisioning process. 

Cheers! :)

**Comment by tomkerswill** [comment]
Hi everyone,

James' repository no longer seems to work... Or at least, I'm now getting a permission denied (ssh) error when trying to clone it. Did this ever get merged into the master, and is anyone still hitting this issue? Does anyone else have any workarounds?!

Thanks

Tom

**Comment by jpudney** [comment]
Hey @tomkerswill,

Apologies, I deleted the repo a while back. Nothing much has happened with regard to this issue.

What issues do you still have? Perhaps worth making those changes to the fork that you've created?

**Comment by tomkerswill** [comment]
Hi James,

Ah great - good thinking. Okay, I've replicated your changes and put them here:

https://github.com/tomkerswill/shopify_api.git

... And then I just changed my composer.json to reference the forked repo --- hopefully creating a similar composer.json will work for others using this. Many thanks for all your work fixing the original issues - helped me get off the ground quickly with my Shopify project! Here's the composer.json:

{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/tomkerswill/shopify_api.git"
        }
    ],
    "minimum-stability": "dev",
    "require": {
        "sandeepshetty/shopify_api": "dev-master"
    }
}

**Comment by jpudney** [comment]
@tomkerswill looks good, you might want to modify your composer to require your repo:

``` json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/tomkerswill/shopify_api.git"
        }
    ],
    "minimum-stability": "dev",
    "require": {
        "tomkerswill/shopify_api": "dev-master"
    }
}
```

**Comment by tomkerswill** [comment]
Hi James! That actually stops it working as it stands --- and I think it's probably because the name of the package is still "sandeepshetty/shopify_api" --- we're simply putting it at a different repository URL. I presume that I could change this line in client.php:

namespace sandeepshetty\shopify_api;

... But I've left it as-is for now. That way, if Sandeep ever does do the fixes, then I can revert back to his package nice and easily!

Thanks for all the help with this,

Tom

**Comment by hsleewis** [comment]
@sandeepshetty or this one? :+1:

**Comment by sirtawast** [comment]
This fixed the problems I had with dev shop / private app combination. Thanks!

**Comment by sandeepshetty** [comment]
This issue and more fixed in the [latest version](https://github.com/phpish/shopify)

**Pull request closed without merging**
